[profile.default]
cache_path = 'forge-cache'
evm_version = 'paris'
libs = ["node_modules", "lib"]
optimizer = false
optimizer_runs = 999
out = "forge-artifacts"
remappings = [
  "forge-std/=lib/forge-std/src/",
  "ds-test/=lib/forge-std/lib/ds-test/src/",
]
#solc_version = '0.8.23'
auto_detect_solc = true
src = "contracts"
test = 'test/foundry'
via_ir = true

rpc_endpoints = {mainnet = "https://rpc.ankr.com/eth", optimism = "https://opt-mainnet.g.alchemy.com/v2/demo", fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum", bsc = "https://rpc.ankr.com/bsc", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", Avalanche = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon", celo = "https://rpc.ankr.com/celo", Base = "https://developer-access-mainnet.base.org", kava = "https://evm.data.kava.chainstacklabs.com", metis = "https://andromeda.metis.io/?owner=1088"}

[fmt]
bracket_spacing = true
func_attrs_with_params_multiline = false
ignore = []
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = 'preserve'
tab_width = 4
variable_override_spacing = true
wrap_comments = false
